---

- name: Clean yum metadata
  command: yum clean metadata
  args:
    warn: no
  become: true 

- name: reload systemd configuration
  become: true
  systemd:
    daemon_reload: true

- name: scylla restart
  become: true
  service:
    name: scylla-server
    state: restarted
    enabled: yes

- name: scylla stop
  become: true
  service:
    name: scylla-server
    state: stopped

- name: Enable and start 'node-exporter.service' service (legacy)
  block:
  - name: Disable and stop 'scylla-node-exporter.service' service
    ansible.builtin.service:
      name: scylla-node-exporter.service
      state: stopped
      enabled: no
    when: ansible_facts.services["scylla-node-exporter.service"] is defined

  - name: Enable and start 'node-exporter.service' service (legacy)
    ansible.builtin.service:
      name: node-exporter.service
      state: started
      enabled: yes
  become: true
  when: ansible_facts.services["node-exporter.service"] is defined

- name: Enable and start 'scylla-node-exporter.service' service
  block:
  - name: Disable and stop 'node-exporter.service' service (legacy)
    ansible.builtin.service:
      name: node-exporter.service
      state: stopped
      enabled: no
    when: ansible_facts.services["node-exporter.service"] is defined

  - name: Enable and start 'scylla-node-exporter.service' service
    ansible.builtin.service:
      name: scylla-node-exporter.service
      state: started
      enabled: yes
  when: ansible_facts.services["scylla-node-exporter.service"] is defined

- name: Enable and start 'scylla-fstrim.timer' service
  ansible.builtin.service:
    name: scylla-fstrim.timer
    state: started
    enabled: yes
  become: true

- name: scylla-manager-agent start
  become: true
  service:
    name: scylla-manager-agent
    state: started
    enabled: true

- name: scylla-manager-agent stop
  become: true
  service:
    name: scylla-manager-agent
    state: stopped

- name: scylla-manager-agent restart
  become: true
  service:
    name: scylla-manager-agent
    state: restarted
