---
- name: Look up scylla_admin password in inventory file
  set_fact:
    _scylla_admin_password_candidate: "{{ lookup('ini', scylla_admin_username | default(scylla_admin_default_user, true), section='cql_credentials', allow_no_value=true, default='', file=iv_file) }}"

- name: Set scylla_admin_password from inventory file
  set_fact:
    scylla_admin_password: "{{ _scylla_admin_password_candidate }}"
    inventory_with_credentials: "{{ iv_file }}"
  when: _scylla_admin_password_candidate | length > 0
