---
- name: Check if {{ scylla_package_prefix }} meta-package is installed
  set_fact:
    scylla_is_installed: "{{ true if scylla_package_prefix in ansible_facts.packages else false }}"

- name: Get installed scylla version
  set_fact:
    installed_scylla_version: "{{ ansible_facts.packages[scylla_package_prefix][0]['version'] }}"
  when: scylla_is_installed

- name: Initialize scylla_version_to_install to {{ scylla_version }}
  set_fact:
    scylla_version_to_install: "{{ scylla_version }}"

- name: Get latest Scylla version if needed
  block:
    - name: Get latest version (non-OSS)
      block:
      - name: Get latest Scylla version
        ansible.builtin.uri:
          url: "https://repositories.scylladb.com/scylla/check_version"
          method: GET
          return_content: true
        register: scylla_latest_version
        when: scylla_edition != 'oss'

      - name: Set scylla_version_to_install to {{ scylla_latest_version.json['version'] }}
        set_fact:
          scylla_version_to_install: "{{ scylla_latest_version.json['version'] }}"
      when: scylla_edition != 'oss'
    
    # The check version API does not return the latest version anymore for the OSS edition.
    # We set the latest version that has been released for the OSS edition.
    - name: Set scylla_version_to_install to 6.2.3 for OSS edition
      set_fact:
        scylla_version_to_install: "6.2.3"
      when: scylla_edition == 'oss'
  when: scylla_version == 'latest' and scylla_install_type == 'online'

- name: "Sanity check: latest version requires online installation type"
  fail:
    msg: "Latest Scylla version can only be installed with an 'online' installation"
  when: scylla_version == 'latest' and scylla_install_type != 'online'
