---
- name: download alert manager archive
  get_url:
    url: "{{ alert_manager_url }}"
    dest: "{{ scylla_monitoring_deploy_path }}"
    mode: '0644'
    owner: "{{ ansible_user_id }}"
  register: alert_manager_archive

- name: unpack the alert_manager archive
  unarchive:
    src: "{{ alert_manager_archive.dest }}"
    dest: "{{ scylla_monitoring_deploy_path }}"
    remote_src: yes
    list_files: yes
  register: alert_manager_files

- set_fact:
    alert_manager_dir: "{{ scylla_monitoring_deploy_path }}/{{ alert_manager_files.files[0] }}"

- name: Copy rule_config.yml from scylla-monitoring/prometheus directory to alertmanager.yml in the alertmanager directory
  copy:
    remote_src: yes
    src: "{{ base_dir }}/prometheus/rule_config.yml"
    dest: "{{ alert_manager_dir }}/alertmanager.yml"
    force: yes

- name: start the alert_manager
  raw: cd {{ alert_manager_dir }}; nohup ./alertmanager </dev/null >/dev/null 2>&1 & sleep 1

- name: wait for alert_manager to start
  wait_for:
    port: 9093
    host: 0.0.0.0
    timeout: 120

- name: download prometheus archive
  get_url:
    url: "{{ prometheus_url }}"
    dest: "{{ scylla_monitoring_deploy_path }}"
    mode: '0644'
    owner: "{{ ansible_user_id }}"
  register: prometheus_archive

- name: unpack the prometheus archive
  unarchive:
    src: "{{ prometheus_archive.dest }}"
    dest: "{{ scylla_monitoring_deploy_path }}"
    remote_src: yes
    list_files: yes
  register: prometheus_files

- set_fact:
    prometheus_dir: "{{ scylla_monitoring_deploy_path }}/{{ prometheus_files.files[0] }}"

- name: copy yml and template files into prometheus
  shell: |
    cp {{ base_dir }}/prometheus/*.yml {{ prometheus_dir }}
    cp -r {{ base_dir }}/prom_rules {{ prometheus_dir }}
    cp {{ base_dir }}/prometheus/*.template {{ prometheus_dir }}

- name: copy prometheus.yml.template to prometheus.yml
  copy:
    remote_src: yes
    src: "{{ prometheus_dir }}/prometheus.yml.template"
    dest: "{{ prometheus_dir }}/prometheus.yml"

- name: Update alertmanager configuration in prometheus
  block:
    - name: set alertmanager address
      replace:
        path: "{{ prometheus_dir }}/prometheus.yml"
        regexp: '^        - AM_ADDRESS'
        replace: '        - 127.0.0.1:9093'

    - name: update prometheus_rules
      replace:
        regexp: '^  - /etc/prometheus/prometheus.rules.yml'
        replace: '  - prometheus.rules.yml'
        path: "{{ prometheus_dir }}/prometheus.yml"

    - name: update prometheus_rules
      replace:
        regexp: '^  - /etc/prometheus/prom_rules/*.yml'
        replace: '  - prom_rules/*.yml'
        path: "{{ prometheus_dir }}/prometheus.yml"

    - name: update prometheus_rules
      replace:
        regexp: '^  - /etc/prometheus/prom_rules/*.yaml'
        replace: '  - prom_rules/*.yaml'
        path: "{{ prometheus_dir }}/prometheus.yml"

    - name: update scylla_servers.yml lines
      replace:
        regexp: '^      - /etc/scylla.d/prometheus/scylla_servers.yml'
        replace: '      - scylla_servers.yml'
        path: "{{ prometheus_dir }}/prometheus.yml"

    - name: update node_exporter_servers.yml lines
      replace:
        regexp: '^      - /etc/scylla.d/prometheus/node_exporter_servers.yml'
        replace: '      - scylla_servers.yml'
        path: "{{ prometheus_dir }}/prometheus.yml"

    - name: update scylla_manager_servers.yml lines
      replace:
        regexp: '^      - /etc/scylla.d/prometheus/scylla_manager_servers.yml'
        replace: '      - scylla_manager_servers.yml'
        path: "{{ prometheus_dir }}/prometheus.yml"

- name: start prometheus
  raw: cd {{ prometheus_dir }} ; nohup ./prometheus --config.file=prometheus.yml --storage.tsdb.path {{ scylla_monitoring_data_path }} --storage.tsdb.retention.time={{ scylla_monitoring_retention }} {{ prometheus_args | default('')}}</dev/null >/dev/null 2>&1 & sleep 1

- name: wait for prometheus to start
  wait_for:
    port: 9090
    host: 0.0.0.0
    timeout: 120





