#!/usr/sbin/ansible-playbook ./async_status_id_recoverable.yml -vvvv
---
- hosts: localhost
  tasks:
    - name: Failed async job
      async_task:
        shell: |
          echo Hello &&
          sleep 10
        alias: blah
        async: 1
        retries: 100
        delay: 5