#!/usr/sbin/ansible-playbook ./async_status_id_recoverable.yml -vvvv
---
- hosts: localhost
  tasks:
    - name: Async recoverable job Blah
      async_task:
        shell: |
          echo Hello &&
          sleep 10
        alias: blah
        async: 1000
        retries: 100
        delay: 5
      register: async_task_obj
    - debug:
        msg: "{{async_task_obj}}"