#!/usr/sbin/ansible-playbook ./async_status_id_recoverable.yml -vvvv
---
- hosts: localhost
  tasks:
    - name: Failed async job
      async_task:
        shell: |
          exit 1
        alias: blah
        async: 1000
        retries: 100
        delay: 5