#!/usr/sbin/ansible-playbook ./async_status_id_recoverable.yml -vvvv
---
- hosts: localhost
  tasks:
    - name: Wait for task to finish
      async_wait:
        alias: fake_blah
        retries: 100
        delay: 5
