#!/usr/sbin/ansible-playbook ./async_status_id_recoverable.yml -vvvv
---
- hosts: localhost
  tasks:
    - name: Check parent poll timeout
      async_task:
        shell: |
          echo Hello &&
          sleep 3600
        alias: blah
        async: 1000
        poll: 5
