#!/usr/sbin/ansible-playbook ./async_status_id_recoverable.yml -vvvv
---
- hosts: localhost
  tasks:
    - name: Do not wait for the task to finish
      async_task:
        shell: |
          echo Hello &&
          sleep 10
        alias: blah
        async: 1000