#!/usr/sbin/ansible-playbook ./async_status_id_recoverable.yml -vvvv
---
- hosts: localhost
  tasks:
    - name: Async recoverable job Blah
      shell: |
        echo Hello &&
        sleep 10
      async: 1000
      poll: 5
      register: async_task_obj
