---

# Start Scylla service
- name: Start Scylla service
  ansible.builtin.service:
    name: scylla-server
    state: started
  notify: scylla-manager-agent restart
  become: true

- name: Wait for CQL port
  wait_for:
    port: 9042
    host: "{{ scylla_listen_address }}"

- name: Wait for nodetool
  ansible.builtin.command: nodetool status
  register: nodetool_ready
  until: nodetool_ready.rc == 0
  retries: 30
  delay: 10
  when: upgrade_sstables | bool
  changed_when: false

- name: Upgrade SSTables to current format
  ansible.builtin.command: nodetool upgradesstables
  register: upgradesstables_result
  when: upgrade_sstables | bool
  async: "{{ upgrade_sstables_timeout_seconds | int }}"
  poll: 30
  changed_when: upgradesstables_result.rc == 0

- name: Upgrade SSTables operation output
  ansible.builtin.debug:
    var: upgradesstables_result
  when: upgrade_sstables | bool
