---

# Ensure apt-transport-https and dirmngr are installed
- name: Ensure apt-transport-https and dirmngr are installed
  ansible.builtin.apt:
    name: [apt-transport-https,dirmngr]
    state: present
  become: true

# Unhold Scylla package in case it's marked as 'hold'
- name: Unhold package name {{ scylla_detected['package_name'] }}*
  ansible.builtin.dpkg_selections:
    name: "{{ scylla_detected['package_name'] }}*"
    selection: install

# Upgrade Scylla
- name: "Upgrade Scylla to {{ scylla_upgrade['version'] }}"
  set_fact:
    scylla_version_to_install: "{{ scylla_upgrade['version'] }}"

- name: Install Scylla packages
  include_tasks: ../Debian.yml
