---

# Ensure apt-transport-https and dirmngr are installed
- name: Ensure apt-transport-https and dirmngr are installed
  ansible.builtin.apt:
    name: [apt-transport-https,dirmngr]
    state: present
  become: true


# Add Scylla apt key
- name: Add Scylla apt key
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 5e08fbd8b5d6ec9c
  become: true


# Remove existing Scylla repositories
- name: Remove existing Scylla repositories
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/scylla.list
    state: absent    
  become: true


# Create Scylla repositories file
- name: Create Scylla repositories file
  ansible.builtin.get_url:
    url: "http://downloads.scylladb.com/deb/debian/scylla-{{ scylla_upgrade['major_version'] }}-{{ ansible_facts['distribution_release'] }}.list"
    dest: /etc/apt/sources.list.d/scylla.list
    mode: '0644'
  become: true


# Unhold Scylla package in case it's marked as 'hold'
- name: Unhold Scylla package
  ansible.builtin.dpkg_selections:
    name: "{{ scylla_detected['package_name'] }}*"
    selection: install


# Upgrade Scylla
- name: "Upgrade Scylla to {{ scylla_upgrade['version'] }}"
  set_fact:
    scylla_version_to_install: "{{ scylla_upgrade['version'] }}"

- name: Install Scylla packages
  include_tasks: ../Debian_install.yml