---

# Remove existing Scylla repositories
- name: Remove existing Scylla repositories
  ansible.builtin.file:
    path: /etc/yum.repos.d/scylla.repo
    state: absent    
  notify: Clean yum metadata  
  become: true
  when: upgrade_major


# Create Scylla repositories file
- name: Create Scylla repositories file
  ansible.builtin.get_url:
    url: "https://downloads.scylladb.com/rpm/centos/scylla-{{ scylla_upgrade['major_version'] }}.repo"
    dest: /etc/yum.repos.d/scylla.repo
    mode: '0644'
  become: true
  when: upgrade_major


# Ensure 'ABRT' is not installed
- name: Ensure 'ABRT' is not installed
  ansible.builtin.yum:
    name: 'abrt'
    state: absent
    lock_timeout: 60
  become: true


# Check if Scylla packages are excluded and remove them from the list
- name: Check if Scylla packages are excluded and remove them from the list        
  ansible.builtin.replace:
    path: /etc/yum.conf
    regexp: 'scylla([*]|[\s.*]|[-]\w+)'
    replace: ''
  become: true
  when: upgrade_major


# Upgrade Scylla 
- name: Upgrade Scylla to {{ scylla_upgrade['version'] }}
  ansible.builtin.yum:
    name: "{{ scylla_detected['package_name'] }}*-{{ scylla_upgrade['version'] }}*"
    state: present
    update_cache: yes
    lock_timeout: 60
  become: true
