---
- block:
  - name: Check if scylla-manager-agent port is open on the scylla nodes
    shell:
      "nc -z -w 2 {{ hostvars[item]['ansible_host'] | default(item) }} {{ scylla_manager_agent_port }}"
    loop: "{{ groups['scylla'] }}"
    when: test_manager_agent_port

  - name: install Scylla Manager
    include_tasks: "{{ ansible_os_family }}.yml"

  - name: run scyllamgr_setup
    shell: |
      scyllamgr_setup -y
    become: true

  - name: start manager
    include_tasks: start_manager.yml

  - name: add Scylla clusters
    include_tasks: add_cluster.yml
    loop: "{{ scylla_clusters }}"
  module_defaults:
    ansible.builtin.apt:
      lock_timeout: "{{ apt_lock_timeout }}"


