---
dependency:
  name: galaxy
  enabled: false
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: node1
    image: jrei/systemd-ubuntu:16.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - scylla
  - name: node2
    image: jrei/systemd-ubuntu:16.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - scylla
  - name: node3
    image: jrei/systemd-ubuntu:16.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - scylla
provisioner:
  name: ansible
  env:
    ANSIBLE_LIBRARY: $PWD/../example-playbooks/async_extra/library
    ANSIBLE_ACTION_PLUGINS: $PWD/../example-playbooks/async_extra/action_plugins
  inventory:
    group_vars:
      scylla:
        scylla_repos:
          - "https://downloads.scylladb.com/deb/ubuntu/scylla-4.4-xenial.list"
        scylla_edition: "oss"
        scylla_io_probe: false
        io_properties:
          disks:
            - mountpoint: "/var/lib/scylla/data"
              read_iops: 100
              read_bandwidth: 1000
              write_iops: 100
              write_bandwidth: 1000
        dc: "test_dc"
        rack: "test_rack"
        scylla_manager_repo_url: "https://downloads.scylladb.com/deb/ubuntu/scylladb-manager-2.3-xenial.list"
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
verifier:
  name: ansible
