---
dependency:
  name: galaxy
  enabled: false
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: node1
    image: jrei/systemd-ubuntu:20.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - scylla
  - name: node2
    image: jrei/systemd-ubuntu:20.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - scylla
  - name: node3
    image: jrei/systemd-ubuntu:20.04
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - scylla
provisioner:
  name: ansible
  log: True
  options:
    vvv: True
  inventory:
    group_vars:
      scylla:
        scylla_deb_repos:
          - "http://downloads.scylladb.com/deb/ubuntu/scylla-2021.1.list"
        scylla_edition: "enterprise"
        scylla_version: "latest"
        scylla_io_probe: false
        io_properties:
          disks:
            - mountpoint: "/var/lib/scylla/data"
              read_iops: 100
              read_bandwidth: 1000
              write_iops: 100
              write_bandwidth: 1000
        scylla_seeds:
          - "172.17.0.2"
        dc: "test_dc"
        rack: "test_rack"
        skip_coredump: True
        skip_sysconfig: True
        skip_cpuset: True
#        skip_ntp: True
        scylla_manager_deb_repo_url: "http://downloads.scylladb.com/deb/ubuntu/scylladb-manager-2.6-bionic.list"
  playbooks:
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml
scenario:
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - verify
verifier:
  name: ansible
