---
name: Molecule Test for ansible-scylla-node role
on:
  push:
    paths:
      - 'ansible-scylla-node/**'
  pull_request:
    paths:
      - 'ansible-scylla-node/**'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro:
          #- centos7
          - centos8
          #- debian9
          #- debian10
          #- fedora
          #- ubuntu1604
          - ubuntu1804
          - ubuntu2004
    defaults:
      run:
        working-directory: ansible-scylla-node
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt requirements-dev.txt
          ansible --version
          molecule --version
      - name: Test with molecule
        run: |
          molecule test --destroy=never --scenario-name ${{ matrix.molecule_distro }}
