---
name: Molecule Test for ansible roles
on:
  push:
    paths:
      - 'ansible-scylla-node/**'
      - 'ansible-scylla-monitoring/**'
      - 'ansible-scylla-manager/**'
      - '.github/workflows/*'
  pull_request:
    paths:
      - 'ansible-scylla-node/**'
      - 'ansible-scylla-monitoring/**'
      - 'ansible-scylla-manager/**'
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro:
          - debian11
          - debian12
          - ubuntu2204
          - ubuntu2404
          - rockylinux9
          - rockylinux10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==25.2 pip-tools
          pip-sync requirements.txt requirements-dev.txt
          ansible-galaxy collection install community.docker
          ansible --version
          molecule --version
      - name: Test with molecule
        run: |
          molecule destroy --scenario-name ${{ matrix.molecule_distro }} && molecule test --scenario-name ${{ matrix.molecule_distro }}
